label_strategy: origin
perc: no
eval_only: no
results_dir: ufbrp/results-cifar10
logs_dir: ufbrp/logs
checkpoints_path: ufbrp/logs/convnext_lipreg_aa-cifar10

data:
  num_classes: 10
  dataset: CIFAR10
  directory: data/CIFAR10

lr_scheduler:
  type: cosine
  T_max: 200
  eta_min: 0

optimizer:
  type: adam
  lr: 0.01
  aa_lr: 0.0003

train:
  aa_reg_alpha: 0.0001
  filt_size: 5
  model: convnext_lipreg_aa
  wavelet_level: 2
  wavelet_method: haar
  jacobian_delta: 0.5
  k: 1.0
  epochs: 200
  num_workers: 4
  batch_size: 128
  val_criterion: Accuracy
 
attack:
  train:
    type: pgd
    params:
      eps: 4.0
      alpha: 2.5
      mode: zero
      iters: 5
  test:
    -
      type: fgsm
      params:
        eps: 8.0
        alpha: 2.5
        mode: zero
    -
      type: pgd
      params:
        eps: 8.0
        alpha: 2.5
        mode: zero
    -
      type: autoattack
      params:
        eps: 8.0
        mode: zero