label_strategy: origin
perc: no
eval_only: no
results_dir: ufbrp/results
logs_dir: ufbrp/logs

data:
  num_classes: 100
  dataset: CIFAR100
  directory: data/CIFAR100

lr_scheduler:
  type: step
  step_size: 30
  gamma: 0.1

optimizer:
  type: adam
  lr: 0.001

train:
  model: resnet50-adv
  epochs: 300
  num_workers: 2
  batch_size: 128
  val_criterion: Accuracy

attack:
  train:
    type: pgd
    params:
      eps: 4.0
      alpha: 2.5
      mode: zero
      iters: 5
  test:
    -
      type: fgsm
      params:
        eps: 8.0
        alpha: 2.5
        mode: zero
    -
      type: pgd
      params:
        eps: 8.0
        alpha: 2.5
        mode: zero
    -
      type: autoattack
      params:
        eps: 8.0
        mode: zero
