label_strategy: origin
perc: no
eval_only: no
results_dir: ufbrp/results-cifar100
logs_dir: ufbrp/logs
checkpoints_path: ufbrp/logs/wideresnet_lipreg_aa-adv-cifar100

data:
  num_classes: 100
  dataset: CIFAR100
  directory: data/CIFAR100

lr_scheduler:
  type: step
  step_size: 50
  gamma: 0.5

optimizer:
  type: adam
  lr: 0.001
  aa_lr: 0.0003

train:
  aa_reg_alpha: 0.0001
  filt_size: 5
  model: wideresnet_lipreg_aa
  wavelet_level: 2
  wavelet_method: haar
  jacobian_delta: 0.5
  k: 1.0
  epochs: 300
  num_workers: 4
  batch_size: 128
  val_criterion: Accuracy

attack:
  train:
    type: pgd
    params:
      eps: 4.0
      alpha: 2.5
      mode: zero
      iters: 1
  test:
    -
      type: fgsm
      params:
        eps: 8.0
        alpha: 2.5
        mode: zero
    -
      type: pgd
      params:
        eps: 8.0
        alpha: 2.5
        mode: zero
    -
      type: autoattack
      params:
        eps: 8.0
        mode: zero
